version: '1.0'
services:
  backend:
    build:
      context: backend/.
      # for alembic I need to pass the DATABASE_URL as an argument during build phase
      args:
        - APP_DATABASE_URL=${DOCKER_DATABASE_URL}
    #    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/usr/src/app
    environment:
      - APP_DATABASE_URL=${DOCKER_DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
